services:
  - type: web
    name: scraping-sia-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    disks:
      - name: data-storage
        mountPath: /app/scraped_data
        sizeGB: 1
  - type: cron
    name: sia-scraper
    env: python
    schedule: "0 * * * *"
    buildCommand: "pip install -r requirements.txt && playwright install"
    command: "python Scraper.py"
    disks:
      - name: data-storage
        mountPath: /app/scraped_data